### ISSUE TITLE
XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by wofdwid** [websemantics/vimeo-upload#21]
0|CE Libra | 2017-08-08 09:05:06 -03:00: ReferenceError: XMLHttpRequest is not defined
0|CE Libra |     at me.upload (/srv/shared/backend/node_modules/vimeo-upload/vimeo-upload.js:193:23)
0|CE Libra |     at /srv/shared/backend/lib/importer/uploadVideo.js:22:45
0|CE Libra |     at Video.get link [as link] (/srv/shared/backend/lib/importer/uploadVideo.js:13:20)
0|CE Libra |     at Object.<anonymous> (/srv/shared/backend/lib/importer/uploadVideo.js:37:57)
0|CE Libra |     at Module._compile (module.js:570:32)
0|CE Libra |     at Module._compile (/srv/shared/backend/node_modules/async-to-gen/register.js:39:23)
0|CE Libra |     at Module._extensions..js (module.js:579:10)
0|CE Libra |     at Object.require.extensions.(anonymous function) [as .js] (/srv/shared/backend/node_modules/async-to-gen/register.js:42:5)
0|CE Libra |     at Module.load (module.js:487:32)
0|CE Libra |     at tryModuleLoad (module.js:446:12)
0|CE Libra |     at Function.Module._load (module.js:438:3)
0|CE Libra |     at Module.require (module.js:497:17)
0|CE Libra |     at require (internal/module.js:20:19)

**Comment by jrfii-animation** [comment]
@pittersnider: I know I'm about 5-years late here, but I was wondering if you were ever able to overcome this error?
